"""Workflow catalog — the single source of numbered workflow definitions.

ID scheme:
    1xx.x  — synthetic mode (fast, no CMSSW)
    15x.x  — simulator mode (fast, no CMSSW, real ROOT/FJR artifacts)
    2xx.x  — single-step CMSSW (GEN)
    3xx.x  — multi-step StepChain
    4xx.x  — pilot workflow
    5xx.x  — fault injection / recovery (synthetic, fast)
    9xx.x  — performance / scale

Variant convention:
    x00.0 = plumbing (2 jobs),  x00.1 = performance (4–8 jobs)
"""

from __future__ import annotations

from tests.matrix.definitions import FaultSpec, VerifySpec, WorkflowDef

# ── Synthetic baseline ────────────────────────────────────────

_SYNTHETIC_OUTPUT = [
    {
        "dataset_name": "/TestPrimary/Test-v1/GEN-SIM",
        "merged_lfn_base": "/store/mc/Test/TestPrimary/GEN-SIM/v1",
        "unmerged_lfn_base": "/store/unmerged/Test/TestPrimary/GEN-SIM/v1",
        "data_tier": "GEN-SIM",
    }
]

_WF_100_0 = WorkflowDef(
    wf_id=100.0,
    title="Synthetic baseline, 1 job",
    sandbox_mode="synthetic",
    request_spec={
        "RequestName": "matrix_synthetic_100_0",
        "RequestType": "StepChain",
        "StepChain": 1,
        "Step1": {
            "StepName": "GEN-SIM",
            "GlobalTag": "auto:mc",
            "CMSSWVersion": "",
        },
        "Multicore": 1,
        "Memory": 512,
        "TimePerEvent": 0.01,
        "SizePerEvent": 1.0,
    },
    events_per_job=1,
    num_jobs=1,
    output_datasets=_SYNTHETIC_OUTPUT,
    memory_mb=512,
    multicore=1,
    size="small",
    timeout_sec=120,
    requires=("condor",),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_100_1 = WorkflowDef(
    wf_id=100.1,
    title="Synthetic baseline, 8 jobs",
    sandbox_mode="synthetic",
    request_spec={
        "RequestName": "matrix_synthetic_100_1",
        "RequestType": "StepChain",
        "StepChain": 1,
        "Step1": {
            "StepName": "GEN-SIM",
            "GlobalTag": "auto:mc",
            "CMSSWVersion": "",
        },
        "Multicore": 1,
        "Memory": 512,
        "TimePerEvent": 0.01,
        "SizePerEvent": 1.0,
    },
    events_per_job=1,
    num_jobs=8,
    output_datasets=_SYNTHETIC_OUTPUT,
    memory_mb=512,
    multicore=1,
    size="medium",
    timeout_sec=300,
    requires=("condor",),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

# ── Multi-step StepChain (real CMSSW via cached sandbox) ──────

_NPS_OUTPUT_DATASETS = [
    {
        "dataset_name": "/ADD-monojet_N-6_MD-6000_TuneCP5_13p6TeV_pythia8/Run3Summer22EEMiniAODv4-130X_mcRun3_2022_realistic_postEE_v6-v2/MINIAODSIM",
        "merged_lfn_base": "/store/mc/Run3Summer22EEMiniAODv4/ADD-monojet_N-6_MD-6000_TuneCP5_13p6TeV_pythia8/MINIAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v2",
        "unmerged_lfn_base": "/store/unmerged/Run3Summer22EEMiniAODv4/ADD-monojet_N-6_MD-6000_TuneCP5_13p6TeV_pythia8/MINIAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v2",
        "data_tier": "MINIAODSIM",
    },
    {
        "dataset_name": "/ADD-monojet_N-6_MD-6000_TuneCP5_13p6TeV_pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM",
        "merged_lfn_base": "/store/mc/Run3Summer22EENanoAODv12/ADD-monojet_N-6_MD-6000_TuneCP5_13p6TeV_pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v2",
        "unmerged_lfn_base": "/store/unmerged/Run3Summer22EENanoAODv12/ADD-monojet_N-6_MD-6000_TuneCP5_13p6TeV_pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v2",
        "data_tier": "NANOAODSIM",
    },
]

_WF_300_0 = WorkflowDef(
    wf_id=300.0,
    title="NPS 5-step StepChain, 1 work unit (2 jobs x 40 ev)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_NPS-Run3Summer22EEGS-00049__v1_T_260126_110934_54",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 1.0,
        "SizePerEvent": 50.0,
    },
    events_per_job=40,
    num_jobs=2,
    output_datasets=_NPS_OUTPUT_DATASETS,
    memory_mb=16000,
    multicore=8,
    size="large",
    timeout_sec=3600,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_GEN_DY2L_OUTPUT_DATASETS = [
    {
        "dataset_name": "/DYto2L-4Jets_MLL-4to50_HT-2500_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Summer22EEMiniAODv4-130X_mcRun3_2022_realistic_postEE_v6-v2/MINIAODSIM",
        "merged_lfn_base": "/store/mc/Run3Summer22EEMiniAODv4/DYto2L-4Jets_MLL-4to50_HT-2500_TuneCP5_13p6TeV_madgraphMLM-pythia8/MINIAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v2",
        "unmerged_lfn_base": "/store/unmerged/Run3Summer22EEMiniAODv4/DYto2L-4Jets_MLL-4to50_HT-2500_TuneCP5_13p6TeV_madgraphMLM-pythia8/MINIAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v2",
        "data_tier": "MINIAODSIM",
    },
    {
        "dataset_name": "/DYto2L-4Jets_MLL-4to50_HT-2500_TuneCP5_13p6TeV_madgraphMLM-pythia8/Run3Summer22EENanoAODv12-130X_mcRun3_2022_realistic_postEE_v6-v2/NANOAODSIM",
        "merged_lfn_base": "/store/mc/Run3Summer22EENanoAODv12/DYto2L-4Jets_MLL-4to50_HT-2500_TuneCP5_13p6TeV_madgraphMLM-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v2",
        "unmerged_lfn_base": "/store/unmerged/Run3Summer22EENanoAODv12/DYto2L-4Jets_MLL-4to50_HT-2500_TuneCP5_13p6TeV_madgraphMLM-pythia8/NANOAODSIM/130X_mcRun3_2022_realistic_postEE_v6-v2",
        "data_tier": "NANOAODSIM",
    },
]

_WF_301_0 = WorkflowDef(
    wf_id=301.0,
    title="DY2L 5-step StepChain, 8 cores (8 jobs x 400 ev, ~10% filter)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox_gen_dy2l.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_GEN-Run3Summer22EEwmLHEGS-00600__v1_T_250902_211552_8573",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 11.35,
        "SizePerEvent": 1570.7,
    },
    events_per_job=400,
    num_jobs=8,
    output_datasets=_GEN_DY2L_OUTPUT_DATASETS,
    memory_mb=16000,
    multicore=8,
    size="large",
    timeout_sec=10800,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_351_0 = WorkflowDef(
    wf_id=351.0,
    title="DY2L adaptive step 1 split (2 jobs x 40 ev, ~10% filter)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox_gen_dy2l.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_GEN-Run3Summer22EEwmLHEGS-00600__v1_T_250902_211552_8573",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 11.35,
        "SizePerEvent": 1570.7,
    },
    events_per_job=40,
    num_jobs=2,
    num_work_units=2,
    adaptive=True,
    output_datasets=_GEN_DY2L_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=2500,
    split_tmpfs=True,
    probe_split=True,
    multicore=8,
    size="large",
    timeout_sec=7200,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_351_1 = WorkflowDef(
    wf_id=351.1,
    title="DY2L adaptive step 1 split (4 jobs x 400 ev, ~10% filter)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox_gen_dy2l.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_GEN-Run3Summer22EEwmLHEGS-00600__v1_T_250902_211552_8573",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 11.35,
        "SizePerEvent": 1570.7,
    },
    events_per_job=400,
    num_jobs=4,
    num_work_units=2,
    adaptive=True,
    output_datasets=_GEN_DY2L_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=2500,
    split_tmpfs=True,
    probe_split=True,
    multicore=8,
    size="large",
    timeout_sec=10800,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

# ── Adaptive job split ────────────────────────────────────────

_WF_391_0 = WorkflowDef(
    wf_id=391.0,
    title="DY2L adaptive job split (2 jobs x 40 ev, ~10% filter)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox_gen_dy2l.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_GEN-Run3Summer22EEwmLHEGS-00600__v1_T_250902_211552_8573",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 11.35,
        "SizePerEvent": 1570.7,
    },
    events_per_job=40,
    num_jobs=2,
    num_work_units=2,
    adaptive=True,
    adaptive_split=False,
    job_split=True,
    split_tmpfs=True,
    probe_split=True,
    output_datasets=_GEN_DY2L_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=2500,
    multicore=8,
    size="large",
    timeout_sec=7200,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_391_1 = WorkflowDef(
    wf_id=391.1,
    title="DY2L adaptive job split (4 jobs x 400 ev, ~10% filter)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox_gen_dy2l.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_GEN-Run3Summer22EEwmLHEGS-00600__v1_T_250902_211552_8573",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 11.35,
        "SizePerEvent": 1570.7,
    },
    events_per_job=400,
    num_jobs=4,
    num_work_units=2,
    adaptive=True,
    adaptive_split=False,
    job_split=True,
    split_tmpfs=True,
    probe_split=True,
    output_datasets=_GEN_DY2L_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=2500,
    multicore=8,
    size="large",
    timeout_sec=10800,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_392_0 = WorkflowDef(
    wf_id=392.0,
    title="DY2L adaptive job split 3-round (2 jobs x 40 ev, 3 GB/core)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox_gen_dy2l.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_GEN-Run3Summer22EEwmLHEGS-00600__v1_T_250902_211552_8573",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 11.35,
        "SizePerEvent": 1570.7,
    },
    events_per_job=40,
    num_jobs=2,
    num_work_units=3,
    adaptive=True,
    adaptive_split=False,
    job_split=True,
    split_tmpfs=True,
    probe_split=True,
    output_datasets=_GEN_DY2L_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=3000,
    multicore=8,
    size="large",
    timeout_sec=10800,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_392_1 = WorkflowDef(
    wf_id=392.1,
    title="DY2L fixed 2T memory test (3 jobs x 10 ev — R1 4337 no tmpfs, R2 6000 tmpfs, R3 4337 tmpfs)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox_gen_dy2l.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_GEN-Run3Summer22EEwmLHEGS-00600__v1_T_250902_211552_8573",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 2,
        "Memory": 4337,
        "TimePerEvent": 11.35,
        "SizePerEvent": 1570.7,
    },
    events_per_job=10,
    num_jobs=3,
    num_work_units=3,
    adaptive=False,
    split_tmpfs=True,
    split_tmpfs_from_wu=1,  # WU0=no tmpfs (baseline), WU1-2=tmpfs
    output_datasets=_GEN_DY2L_OUTPUT_DATASETS,
    memory_mb=4337,
    memory_mb_per_wu={1: 6000},  # R2 gets 6 GB to measure full tmpfs profile
    multicore=2,
    size="large",
    timeout_sec=3600,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=False,  # R3 expected to OOM (tmpfs at 4337 MB)
    ),
)

_WF_391_2 = WorkflowDef(
    wf_id=391.2,
    title="DY2L adaptive job split (4 jobs x 400 ev, 3 GB/core)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox_gen_dy2l.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_GEN-Run3Summer22EEwmLHEGS-00600__v1_T_250902_211552_8573",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 11.35,
        "SizePerEvent": 1570.7,
    },
    events_per_job=400,
    num_jobs=4,
    num_work_units=2,
    adaptive=True,
    adaptive_split=False,
    job_split=True,
    split_tmpfs=True,
    probe_split=True,
    output_datasets=_GEN_DY2L_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=3000,
    multicore=8,
    size="large",
    timeout_sec=10800,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_391_3 = WorkflowDef(
    wf_id=391.3,
    title="DY2L adaptive 3-round no-probe (8T, 2 GB/core, no tmpfs R1, 10% margin)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox_gen_dy2l.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_GEN-Run3Summer22EEwmLHEGS-00600__v1_T_250902_211552_8573",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 11.35,
        "SizePerEvent": 1570.7,
    },
    events_per_job=400,
    num_jobs=4,
    num_work_units=3,
    adaptive=True,
    adaptive_split=False,
    job_split=True,
    split_tmpfs=True,
    split_tmpfs_from_wu=1,
    probe_split=False,
    output_datasets=_GEN_DY2L_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=3000,
    safety_margin=0.10,
    multicore=8,
    size="large",
    timeout_sec=16200,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

# ── Adaptive execution ────────────────────────────────────────

_WF_350_0 = WorkflowDef(
    wf_id=350.0,
    title="Adaptive nThreads tuning, 40 ev/job",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_NPS-Run3Summer22EEGS-00049__v1_T_260126_110934_54",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 1.0,
        "SizePerEvent": 50.0,
    },
    events_per_job=40,
    num_jobs=2,
    num_work_units=2,
    adaptive=True,
    output_datasets=_NPS_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=2000,
    multicore=8,
    size="large",
    timeout_sec=7200,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_360_0 = WorkflowDef(
    wf_id=360.0,
    title="Adaptive overcommit only (no step 0 split)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_NPS-Run3Summer22EEGS-00049__v1_T_260126_110934_54",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 1.0,
        "SizePerEvent": 50.0,
    },
    events_per_job=40,
    num_jobs=8,
    num_work_units=2,
    adaptive=True,
    adaptive_split=False,
    overcommit_max=1.25,
    output_datasets=_NPS_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=2000,
    multicore=8,
    size="large",
    timeout_sec=7200,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_370_0 = WorkflowDef(
    wf_id=370.0,
    title="Adaptive split + overcommit (1.25x max)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_NPS-Run3Summer22EEGS-00049__v1_T_260126_110934_54",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 1.0,
        "SizePerEvent": 50.0,
    },
    events_per_job=40,
    num_jobs=8,
    num_work_units=2,
    adaptive=True,
    overcommit_max=1.25,
    output_datasets=_NPS_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=2000,
    multicore=8,
    size="large",
    timeout_sec=7200,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_380_0 = WorkflowDef(
    wf_id=380.0,
    title="Adaptive all-step pipeline split",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_NPS-Run3Summer22EEGS-00049__v1_T_260126_110934_54",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 1.0,
        "SizePerEvent": 50.0,
    },
    events_per_job=40,
    num_jobs=8,
    num_work_units=2,
    adaptive=True,
    adaptive_split=False,
    split_all_steps=True,
    output_datasets=_NPS_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=2000,
    multicore=8,
    size="large",
    timeout_sec=7200,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_380_1 = WorkflowDef(
    wf_id=380.1,
    title="Pipeline split, uniform threads, 400 ev/job",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_NPS-Run3Summer22EEGS-00049__v1_T_260126_110934_54",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 1.0,
        "SizePerEvent": 50.0,
    },
    events_per_job=400,
    num_jobs=8,
    num_work_units=2,
    adaptive=True,
    adaptive_split=False,
    split_all_steps=True,
    split_uniform_threads=True,
    output_datasets=_NPS_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=2000,
    multicore=8,
    size="large",
    timeout_sec=72000,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_300_1 = WorkflowDef(
    wf_id=300.1,
    title="NPS 5-step StepChain, 16-core jobs (4 jobs x 1000 ev)",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_NPS-Run3Summer22EEGS-00049__v1_T_260126_110934_54",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 16,
        "Memory": 32000,
        "TimePerEvent": 1.0,
        "SizePerEvent": 50.0,
    },
    events_per_job=1000,
    num_jobs=4,
    output_datasets=_NPS_OUTPUT_DATASETS,
    memory_mb=32000,
    multicore=16,
    size="large",
    timeout_sec=36000,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_350_1 = WorkflowDef(
    wf_id=350.1,
    title="Adaptive nThreads tuning, 10 ev/job",
    sandbox_mode="cached",
    cached_sandbox_path="/mnt/shared/work/wms2_real_condor_test/sandbox.tar.gz",
    request_spec={
        "RequestName": "cmsunified_task_NPS-Run3Summer22EEGS-00049__v1_T_260126_110934_54",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 1.0,
        "SizePerEvent": 50.0,
    },
    events_per_job=10,
    num_jobs=8,
    num_work_units=2,
    adaptive=True,
    output_datasets=_NPS_OUTPUT_DATASETS,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=2000,
    multicore=8,
    size="large",
    timeout_sec=3600,
    requires=("condor", "cvmfs", "siteconf", "apptainer"),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

# ── Fault injection ───────────────────────────────────────────

_WF_500_0 = WorkflowDef(
    wf_id=500.0,
    title="Fault: proc exits 1 (retry then rescue)",
    sandbox_mode="synthetic",
    request_spec={
        "RequestName": "matrix_fault_500_0",
        "RequestType": "StepChain",
        "StepChain": 1,
        "Step1": {
            "StepName": "GEN-SIM",
            "GlobalTag": "auto:mc",
            "CMSSWVersion": "",
        },
        "Multicore": 1,
        "Memory": 512,
        "TimePerEvent": 0.01,
        "SizePerEvent": 1.0,
    },
    events_per_job=1,
    num_jobs=1,
    output_datasets=_SYNTHETIC_OUTPUT,
    memory_mb=512,
    multicore=1,
    size="medium",
    timeout_sec=300,
    requires=("condor",),
    fault=FaultSpec(target="proc", exit_code=1),
    verify=VerifySpec(
        expect_success=False,
        expect_rescue_dag=True,
        expect_merged_outputs=False,
        expect_cleanup_ran=False,
    ),
)

_WF_501_0 = WorkflowDef(
    wf_id=501.0,
    title="Fault: proc SIGKILL",
    sandbox_mode="synthetic",
    request_spec={
        "RequestName": "matrix_fault_501_0",
        "RequestType": "StepChain",
        "StepChain": 1,
        "Step1": {
            "StepName": "GEN-SIM",
            "GlobalTag": "auto:mc",
            "CMSSWVersion": "",
        },
        "Multicore": 1,
        "Memory": 512,
        "TimePerEvent": 0.01,
        "SizePerEvent": 1.0,
    },
    events_per_job=1,
    num_jobs=2,
    output_datasets=_SYNTHETIC_OUTPUT,
    memory_mb=512,
    multicore=1,
    size="small",
    timeout_sec=120,
    requires=("condor",),
    fault=FaultSpec(target="proc", signal=9),
    verify=VerifySpec(
        expect_success=False,
        expect_rescue_dag=True,
        expect_merged_outputs=False,
        expect_cleanup_ran=False,
    ),
)

_WF_510_0 = WorkflowDef(
    wf_id=510.0,
    title="Fault: merge exits 1",
    sandbox_mode="synthetic",
    request_spec={
        "RequestName": "matrix_fault_510_0",
        "RequestType": "StepChain",
        "StepChain": 1,
        "Step1": {
            "StepName": "GEN-SIM",
            "GlobalTag": "auto:mc",
            "CMSSWVersion": "",
        },
        "Multicore": 1,
        "Memory": 512,
        "TimePerEvent": 0.01,
        "SizePerEvent": 1.0,
    },
    events_per_job=1,
    num_jobs=2,
    output_datasets=_SYNTHETIC_OUTPUT,
    memory_mb=512,
    multicore=1,
    size="small",
    timeout_sec=120,
    requires=("condor",),
    fault=FaultSpec(target="merge", exit_code=1),
    verify=VerifySpec(
        expect_success=False,
        expect_rescue_dag=True,
        expect_merged_outputs=False,
        expect_cleanup_ran=False,
    ),
)

# ── Simulator mode ────────────────────────────────────────────

_SIM_OUTPUT_5STEP = [
    {
        "dataset_name": "/TestPrimary/Test-v1/GEN-SIM",
        "merged_lfn_base": "/store/mc/Test/TestPrimary/GEN-SIM/v1",
        "unmerged_lfn_base": "/store/unmerged/Test/TestPrimary/GEN-SIM/v1",
        "data_tier": "GEN-SIM",
    },
    {
        "dataset_name": "/TestPrimary/Test-v1/DIGI",
        "merged_lfn_base": "/store/mc/Test/TestPrimary/DIGI/v1",
        "unmerged_lfn_base": "/store/unmerged/Test/TestPrimary/DIGI/v1",
        "data_tier": "DIGI",
    },
    {
        "dataset_name": "/TestPrimary/Test-v1/RECO",
        "merged_lfn_base": "/store/mc/Test/TestPrimary/RECO/v1",
        "unmerged_lfn_base": "/store/unmerged/Test/TestPrimary/RECO/v1",
        "data_tier": "RECO",
    },
    {
        "dataset_name": "/TestPrimary/Test-v1/MINIAODSIM",
        "merged_lfn_base": "/store/mc/Test/TestPrimary/MINIAODSIM/v1",
        "unmerged_lfn_base": "/store/unmerged/Test/TestPrimary/MINIAODSIM/v1",
        "data_tier": "MINIAODSIM",
    },
    {
        "dataset_name": "/TestPrimary/Test-v1/NANOAODSIM",
        "merged_lfn_base": "/store/mc/Test/TestPrimary/NANOAODSIM/v1",
        "unmerged_lfn_base": "/store/unmerged/Test/TestPrimary/NANOAODSIM/v1",
        "data_tier": "NANOAODSIM",
    },
]

_WF_160_0 = WorkflowDef(
    wf_id=160.0,
    title="Production-path simulator 5-step, 2 jobs",
    sandbox_mode="simulator",
    request_spec={
        "RequestName": "matrix_prod_160_0",
        "RequestType": "StepChain",
        "StepChain": 5,
        "Step1": {"StepName": "GEN-SIM"},
        "Step2": {"StepName": "DIGI"},
        "Step3": {"StepName": "RECO"},
        "Step4": {"StepName": "MINIAODSIM"},
        "Step5": {"StepName": "NANOAODSIM"},
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 0.05,
        "SizePerEvent": 50.0,
        "SplittingAlgo": "EventBased",
        "SplittingParams": {"events_per_job": 10},
        "InputDataset": "",
        "Requestor": "integration-test",
        "Campaign": "NPS-Run3Summer22EEGS",
        "Priority": 100000,
    },
    events_per_job=10,
    num_jobs=2,
    output_datasets=_SIM_OUTPUT_5STEP,
    memory_mb=16000,
    multicore=8,
    size="medium",
    timeout_sec=600,
    requires=("condor",),
    production_path=True,
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_SIM_OUTPUT_1TIER = [
    {
        "dataset_name": "/TestPrimary/Test-v1/GEN-SIM",
        "merged_lfn_base": "/store/mc/Test/TestPrimary/GEN-SIM/v1",
        "unmerged_lfn_base": "/store/unmerged/Test/TestPrimary/GEN-SIM/v1",
        "data_tier": "GEN-SIM",
    }
]

_SIM_OUTPUT_3TIER = [
    {
        "dataset_name": "/TestPrimary/Test-v1/GEN-SIM",
        "merged_lfn_base": "/store/mc/Test/TestPrimary/GEN-SIM/v1",
        "unmerged_lfn_base": "/store/unmerged/Test/TestPrimary/GEN-SIM/v1",
        "data_tier": "GEN-SIM",
    },
    {
        "dataset_name": "/TestPrimary/Test-v1/DIGI",
        "merged_lfn_base": "/store/mc/Test/TestPrimary/DIGI/v1",
        "unmerged_lfn_base": "/store/unmerged/Test/TestPrimary/DIGI/v1",
        "data_tier": "DIGI",
    },
    {
        "dataset_name": "/TestPrimary/Test-v1/RECO",
        "merged_lfn_base": "/store/mc/Test/TestPrimary/RECO/v1",
        "unmerged_lfn_base": "/store/unmerged/Test/TestPrimary/RECO/v1",
        "data_tier": "RECO",
    },
]

_WF_150_0 = WorkflowDef(
    wf_id=150.0,
    title="Simulator single-step, 1 job",
    sandbox_mode="simulator",
    request_spec={
        "RequestName": "matrix_sim_150_0",
        "RequestType": "StepChain",
        "StepChain": 1,
        "Step1": {"StepName": "GEN-SIM"},
        "Multicore": 4,
        "Memory": 4096,
        "TimePerEvent": 0.05,
        "SizePerEvent": 50.0,
    },
    events_per_job=10,
    num_jobs=1,
    output_datasets=_SIM_OUTPUT_1TIER,
    memory_mb=4096,
    multicore=4,
    size="small",
    timeout_sec=120,
    requires=("condor",),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_150_1 = WorkflowDef(
    wf_id=150.1,
    title="Simulator single-step, 4 jobs",
    sandbox_mode="simulator",
    request_spec={
        "RequestName": "matrix_sim_150_1",
        "RequestType": "StepChain",
        "StepChain": 1,
        "Step1": {"StepName": "GEN-SIM"},
        "Multicore": 4,
        "Memory": 4096,
        "TimePerEvent": 0.05,
        "SizePerEvent": 50.0,
    },
    events_per_job=10,
    num_jobs=4,
    output_datasets=_SIM_OUTPUT_1TIER,
    memory_mb=4096,
    multicore=4,
    size="small",
    timeout_sec=180,
    requires=("condor",),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_151_0 = WorkflowDef(
    wf_id=151.0,
    title="Simulator 3-step StepChain, 2 jobs",
    sandbox_mode="simulator",
    request_spec={
        "RequestName": "matrix_sim_151_0",
        "RequestType": "StepChain",
        "StepChain": 3,
        "Step1": {"StepName": "GEN-SIM"},
        "Step2": {"StepName": "DIGI"},
        "Step3": {"StepName": "RECO"},
        "Multicore": 8,
        "Memory": 8192,
        "TimePerEvent": 0.05,
        "SizePerEvent": 50.0,
    },
    events_per_job=10,
    num_jobs=2,
    output_datasets=_SIM_OUTPUT_3TIER,
    memory_mb=8192,
    multicore=8,
    size="small",
    timeout_sec=180,
    requires=("condor",),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_152_0 = WorkflowDef(
    wf_id=152.0,
    title="Simulator high-memory profile",
    sandbox_mode="simulator",
    request_spec={
        "RequestName": "matrix_sim_152_0",
        "RequestType": "StepChain",
        "StepChain": 1,
        "Step1": {"StepName": "GEN-SIM"},
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 0.05,
        "SizePerEvent": 50.0,
    },
    events_per_job=10,
    num_jobs=2,
    output_datasets=_SIM_OUTPUT_1TIER,
    memory_mb=16000,
    multicore=8,
    size="small",
    timeout_sec=180,
    requires=("condor",),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_155_0 = WorkflowDef(
    wf_id=155.0,
    title="Simulator adaptive 2-WU probe split",
    sandbox_mode="simulator",
    request_spec={
        "RequestName": "matrix_sim_155_0",
        "RequestType": "StepChain",
        "StepChain": 3,
        "Step1": {"StepName": "GEN-SIM"},
        "Step2": {"StepName": "DIGI"},
        "Step3": {"StepName": "RECO"},
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 0.05,
        "SizePerEvent": 50.0,
    },
    events_per_job=10,
    num_jobs=2,
    num_work_units=2,
    adaptive=True,
    output_datasets=_SIM_OUTPUT_3TIER,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=2500,
    probe_split=True,
    multicore=8,
    size="medium",
    timeout_sec=300,
    requires=("condor",),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_155_1 = WorkflowDef(
    wf_id=155.1,
    title="Simulator adaptive job split",
    sandbox_mode="simulator",
    request_spec={
        "RequestName": "matrix_sim_155_1",
        "RequestType": "StepChain",
        "StepChain": 3,
        "Step1": {"StepName": "GEN-SIM"},
        "Step2": {"StepName": "DIGI"},
        "Step3": {"StepName": "RECO"},
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 0.05,
        "SizePerEvent": 50.0,
    },
    events_per_job=10,
    num_jobs=2,
    num_work_units=2,
    adaptive=True,
    adaptive_split=False,
    job_split=True,
    probe_split=True,
    output_datasets=_SIM_OUTPUT_3TIER,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=2500,
    multicore=8,
    size="medium",
    timeout_sec=300,
    requires=("condor",),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

_WF_155_2 = WorkflowDef(
    wf_id=155.2,
    title="Simulator adaptive job split 3-round, 3 GB/core",
    sandbox_mode="simulator",
    request_spec={
        "RequestName": "matrix_sim_155_2",
        "RequestType": "StepChain",
        "StepChain": 3,
        "Step1": {"StepName": "GEN-SIM"},
        "Step2": {"StepName": "DIGI"},
        "Step3": {"StepName": "RECO"},
        "Multicore": 8,
        "Memory": 16000,
        "TimePerEvent": 0.05,
        "SizePerEvent": 50.0,
    },
    events_per_job=10,
    num_jobs=2,
    num_work_units=3,
    adaptive=True,
    adaptive_split=False,
    job_split=True,
    probe_split=True,
    split_tmpfs=True,
    output_datasets=_SIM_OUTPUT_3TIER,
    memory_per_core_mb=2000,
    max_memory_per_core_mb=3000,
    multicore=8,
    size="large",
    timeout_sec=900,
    requires=("condor",),
    verify=VerifySpec(
        expect_success=True,
        expect_merged_outputs=True,
        expect_cleanup_ran=True,
    ),
)

# ── Master catalog ────────────────────────────────────────────

CATALOG: dict[float, WorkflowDef] = {
    wf.wf_id: wf
    for wf in [
        _WF_100_0,
        _WF_100_1,
        _WF_160_0,
        _WF_150_0,
        _WF_150_1,
        _WF_151_0,
        _WF_152_0,
        _WF_155_0,
        _WF_155_1,
        _WF_155_2,
        _WF_300_0,
        _WF_300_1,
        _WF_301_0,
        _WF_351_0,
        _WF_351_1,
        _WF_391_0,
        _WF_391_1,
        _WF_391_2,
        _WF_391_3,
        _WF_392_0,
        _WF_392_1,
        _WF_350_0,
        _WF_360_0,
        _WF_370_0,
        _WF_380_0,
        _WF_380_1,
        _WF_350_1,
        _WF_500_0,
        _WF_501_0,
        _WF_510_0,
    ]
}
